spring:
  datasource:
    name: railway
    url: jdbc:mysql://127.0.0.1:3306/railwayData
    username: root
    password: Yangguang52199！
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml
server:
  port: 8080
#logging:
#  config: classpath:logback.xml
#  level:
#    com.railway.manager: debug
#  path: /data/logs